### ISSUE TITLE
[Task]: Minimize native menu

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#10]
### Task description

Leave only
- [x] About legacy migration tool
- [x] Diagnostics
- [x] Error log
- [x] Discord
- [x] Report an issue

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
