### ISSUE TITLE
[Task]: Update CI

### ISSUE THREAD

**Issue by cpl121** [iotaledger/legacy-migration-tool#104]
### Task description

- [x] uncomment the code for sentry
- [x] modify the tag to make the release, from `desktop` to `v`
- [x] Fix errors to build artifacts
