### ISSUE TITLE
[Task]: Update CI

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#11]
### Task description

- [ ] Update app name to be "IOTA Legacy Migration Tool"
- [ ] Do not upload artifacts, check `packages/desktop/electron-builder-config.js`, we should not upload anything

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
