### ISSUE TITLE
[Task]: Cleanup code [low]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#121]
### Task description

-  [x] 1. Unused constant
Severity: Low
File: migration.ts
Constant: PERMANODE
Details: The given constant was used in the removed code parts.
Recommendation: Remove the constant declaration

-  [x] 2. Function parameter never used
File: TransferFragmentedFunds.svelte
Function: migrateFunds
Details: The function has a parameter declared as "isRerun?: boolean", however, it is never used in the function code. Looking for the function calls we can differentiate the two types of call: without parameter (defaulting to false) and with true as a value (from the rerunMigration function). 
Recommendation: Double-check the functionality and remove the parameter if there is no need for it	

-  [x] 3. Unused variables
File: Welcome.svelte
Variables: error, busy
Details: There are two global variables added in the given file, and their values even being assigned during the execution, but never read
Recommendation: Double-check the functionality and remove the parameters if there is no need for those

-  [x] 4. Using strings in the function
File: Congratulations.svelte
Function: consultExplorerClick
Details: In the function, there is a variable "urlToOpen", which is being assigned to a URL of the explorer depending on either developer account being used or not. It is better, for refactoring and possible next modifications, to keep them outside the function and declare them as constants
Recommendation: Declare URL string prefixes as constants

-  [x] 5. TODOs in the code
File: Balance.svelte
Details: There are multiple "TODO"s in the given file. 
Recommendation: Double check needed implementation is done and remove TODO tags

-  [x] 6. Unused variables
File: Migrate.svelte
Variable: singleMigrationBundleHash
Details: There is a global variable added in the given file, and its value even being assigned during the execution, but never read
Recommendation: Double-check the functionality and remove the parameter if there is no need for it
