### ISSUE TITLE
[Task]: Cleanup code [informational]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#122]
### Task description

-  [x] 7. Function could be declared as async
File: migration.ts
Function: getLedgerMigrationData
Details: The given function is already asynchronous, but adding an "async" keyword to it will make it more visible for debugging/refactoring in the future
Recommendation: Convert function declaration to an "async" with "export const getLedgerMigrationData = async ("	

-  [x] 8. Function parameter is not described in the JSDoc 
File: migration.ts
Function: createLedgerMigrationBundle
Parameters: migrationAddress, callback
Details: The given parameters are present in the function, however, they are not described in the JSDoc
Recommendation: Describe all function parameters in the JSDoc

-  [x] 9. Function parameter is not described in the JSDoc 
File: migration.ts
Function: sendOffLedgerMigrationRequest
Parameters: bundleIndex
Details: The given parameters are present in the function, however, they are not described in the JSDoc
Recommendation: Describe all function parameters in the JSDoc

-  [x] 10. Function parameters are inconsistent with the JSDoc 
File: migration.ts
Function: createMigrationBundle
Parameters: bundle
Details: The given parameters are present in the function, however they are not described in the JSDoc, instead JSDoc contains the bundleIndex parameter
Recommendation: Describe all function parameters in the JSDoc

-  [x] 11. Local variable is redudant
File: migration.ts
Function: fetchReceiptForRequest
Variable: receipt
Details: The receipt variable is being set on line#943, and right after that, it is returned from the function.
Recommendation: Instead of assigning the result of the "response.json()" to a local variable, return its value from the function directly		

-  [x] 12. Function parameter is not described in the JSDoc 
File: migration.ts
Function: assignBundleHash
Parameters: didMine
Details: The given parameters are present in the function, however, they are not described in the JSDoc
Recommendation: Describe all function parameters in the JSDoc

-  [x] 13. Function parameters are inconsistent with the JSDoc 
File: migration.ts
Function: updateLedgerBundleState
Parameters: migrationBundleCrackability
Details: The given parameters are present in the function, however they are not described in the JSDoc, instead JSDoc contains the migrationBundleCrackability parameter
Recommendation: Describe all function parameters in the JSDoc

-  [x] 14. Local variable is redudant
File: migration.ts
Function: createMigrationBundle
Variable: bundleTrytes
Details: The receipt variable is being set on line#866, and right after that, it is returned from the function.
Recommendation: Instead of assigning the result of the "prepareTransfers()" to a local variable, return its value from the function directly
