### ISSUE TITLE
[Task Tracker]: Remove debris

### ISSUE THREAD

**Issue by evavirseda** [iotaledger/legacy-migration-tool#17]
### Task description

- [x] #26 
- [x] https://github.com/iotaledger/legacy-migration-tool/issues/27

### Requirements

TBD

### Acceptance criteria

Remove debris

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
