### ISSUE TITLE
[Task]: Clarify and implement pin changes

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#20]
### Task description

What do we do with tthe pin? The pin is used to encrypt the DDBB, so:
- [ ] Can we skip it? is this a security issue?
- [ ] Should we set a random one? is this a security issue?

### Requirements

Clarify and implement pin changes

### Acceptance criteria

Clarify and implement pin changes

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
