### ISSUE TITLE
[Task]: Remove locales

### ISSUE THREAD

**Issue by evavirseda** [iotaledger/legacy-migration-tool#24]
### Task description

Since we are not going to use several languages, we should remove localities and everything related to internalization

### Requirements

- [ ] Remove locales
- [ ] Remove i18n

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
