### ISSUE TITLE
[Task]: Prepare ISC legacy migration local setup

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#29]
### Task description

Instructions https://github.com/iotaledger/wasp/blob/legacy-migration/README.md
The snapshot CSV for testing purposes was provided in slack

### Requirements

- [ ] I, @cpl121, have a working setup
- [x] I, @brancoder, have a working setup
- [ ] I, @begonaalvarezd, have a working setup 

### Acceptance criteria

All devs in the requirements section have ticked the working setup

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
