### ISSUE TITLE
[Task Tracker]: Adapt `getMigrationData` to new setup

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#31]
### Task description

The very first logic we dont have working regarding migration seems to be `getMigrationData`, we need to make the necessary changes (if we can, otherwise talk to the SDK team) so we can get the data needed for the migration

- [x] #39
- [x] #40
- [ ] #41
- [x] #42

### Requirements

Adapt `getMigrationData` to new setup

### Acceptance criteria

Adapt `getMigrationData` to new setup

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
