### ISSUE TITLE
[Task]: Skip the legal page when user has accepted the latest version already

### ISSUE THREAD

**Issue by VmMad** [iotaledger/legacy-migration-tool#36]
### Task description

Right now the legal page shows even though the user has accepted the latest versions of "Privacy Policy" & "Terms of Service".
We should check local storage before routing to this page

### Requirements
Route to legal page if: 
- [ ] User has not accepted both
- [ ] The local storage has accepted versions but are not on the latest version

### Acceptance criteria

Skip the legal page when user has accepted the latest version already

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
