### ISSUE TITLE
[Task]: Update onboarding to be migration only

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#5]
### Task description

- [x] Skip language list, use english
- [x] Skip appearance screen, use system
- [x] Skip profile name screen, set a random name
- [x] Skip setup a wallet, users should only be allowed to migrate
- [x] Allow only migrating using 81 characters, a seedvault file (needs file validation), or a trinity ledger backup

### Requirements

TBD

### Acceptance criteria

Update onboarding to be migration only

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
