### ISSUE TITLE
[Task]: Update congratulations

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#7]
### Task description

We should not allow the user to enter/login their profile when reaching congratulatios, so we should simply add 3 buttons:
- [ ] export migration log (primary button)
- [ ] export stronghold (if sw profile)
- [ ] migrate another profile

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
