### ISSUE TITLE
[Task]: Remove Firefly branding

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/legacy-migration-tool#9]
### Task description

- [x] Logos
- [x] Texts referencing "Firefly", replace with "IOTA Legacy Migration Tool"

### Requirements

TBD

### Acceptance criteria

TBD

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
