### ISSUE TITLE
[Task]: research how to track a failed migration

### ISSUE THREAD

**Issue by cpl121** [iotaledger/legacy-migration-tool#91]
### Task description

In addition to having the `migration log` file, what can be done to pull the migration thread.
suggestions:

- [x] The `migration log` file can only be exported once the migration has been completed. Does it make sense to export the migration log file in the migrate view?
- [x] If a migration has gone wrong, what more data could we use to find the problem?
- [x] Is the information obtained with the `request id` sufficient?
- [x] Add error message for failed migrations
- [x] Clean unnecessary params of migration log file
- [x] Unify names
- [x] Add the entire request data
- [ ] Add errors to error log
